export const elementFormSchema: Record<string, string[]> = {
  section: [
    "label",
    "position.x",
    "position.y",
    "rotation",
    "fill",
    "width",
    "height",
    "text",
    "stroke",
    "strokeWidth",
  ],
  wall: ["width", "height", "rotation"],
  stage: ["label", "width", "height", "fill"],
  seat: [
    "label",
    "fill",
    "width",
    "price",
    "height",
    "rotation",
    "position.x",
    "position.y",
    "text",
    "stroke",
    "strokeWidth",
    "seatType",
  ],
  door: ["width", "height", "rotation", "fill", "stroke", "strokeWidth"],
  light: ["width", "height", "rotation", "fill", "stroke", "strokeWidth"],
  controlRoom: ["width", "height", "rotation"],
};
