export const elementFormSchema: Record<string, string[]> = {
  section: [
    "label",
    "position.x",
    "position.y",
    "rotation",
    "fill",
    "width",
    "height",
    "text",
    "stroke",
    "strokeWidth",
  ],
  wall: [
    "label",
    "width",
    "height",
    "rotation",
    "position.x",
    "position.y",
    "fill",
  ],
  stage: [
    "label",
    "width",
    "height",
    "fill",
    "position.x",
    "position.y",
    "rotation",
  ],
  seat: [
    "label",
    "fill",
    "width",
    "price",
    "height",
    "rotation",
    "position.x",
    "position.y",
    "text",
    "stroke",
    "strokeWidth",
    "seatType",
  ],
  door: [
    "label",
    "width",
    "height",
    "fill",
    "stroke",
    "strokeWidth",
    "position.x",
    "position.y",
    "rotation",
  ],
  light: [
    "label",
    "width",
    "height",
    "fill",
    "stroke",
    "strokeWidth",
    "position.x",
    "position.y",
    "rotation",
  ],
  controlRoom: [
    "label",
    "width",
    "height",
    "position.x",
    "position.y",
    "fill",
    "rotation",
  ],
};
